const subjectsList = [
  "Math",
  "Test Preparation",
  "English",
  "Science",
  "Language",
  "Social Studies",
  "Computer",
  "Other",
  "Art",
  "Professional",
  "Music",
  "Athletics",
  "ACT",
  "SAT",
  "Actuarial Science",
  "Algebra 1",
  "Algebra 2",
  "Common Core",
  "Calculus",
  "Differential Equations",
  "Discrete Math",
  "Econometrics",
  "Elementary Math",
  "Finite Math",
  "Geometry",
  "Linear Algebra",
  "Logic",
  "Prealgebra",
  "Precalculus",
  "Probability",
  "Statistics",
  "Trigonometry",
  "ACT Writing",
  "ACT Math",
  "ACT Reading",
  "ACT Science",
  "Bar Exam",
  "CAHSEE",
  "CBEST",
  "CFA",
  "CLAST",
  "College Counseling",
  "COOP/HSPT",
  "DAT",
  "GED",
  "GMAT",
  "GRE",
  "IELTS",
  "ISEE",
  "LSAT",
  "MCAT",
  "OLSAT",
  "NCLEX",
  "Praxis",
  "PSAT",
  "Regents",
  "SAT Math",
  "SAT Reading",
  "SAT Writing",
  "SSAT",
  "STAAR",
  "TOEFL",
  "English (K-8)",
  "High School Level English",
  "College Level English",
  "ESL/ESOL",
  "Essay Writing",
  "Grammar",
  "Literature",
  "Reading &amp; Comprehension",
  "Phonics",
  "Proofreading",
  "Study Skills",
  "Vocabulary",
  "Anatomy",
  "Anthropology",
  "Archaeology",
  "Astronomy",
  "Biochemistry",
  "Biology",
  "Biomedical Engineering",
  "Biostatistics",
  "Botany",
  "Chemical Engineering",
  "Chemistry",
  "Civil Engineering",
  "Dentistry",
  "Earth Science",
  "Ecology",
  "Electrical Engineering",
  "Environmental Science",
  "Genetics",
  "Geology",
  "Health Science",
  "Life Sciences",
  "Mechanical Engineering",
  "Microbiology",
  "Nursing",
  "Nutrition",
  "Organic Chemistry",
  "Pharmacology",
  "Physical Science",
  "Physics",
  "Physiology",
  "Psychology",
  "Sociology",
  "Zoology",
  "Arabic",
  "Braille",
  "Bulgarian",
  "Cantonese",
  "Chinese",
  "Czech",
  "Dutch",
  "Farsi",
  "French",
  "German",
  "Greek",
  "Hebrew",
  "Hindi",
  "Hungarian",
  "Indonesian",
  "Italian",
  "Japanese",
  "Korean",
  "Latin",
  "Polish",
  "Portuguese",
  "Public Speaking",
  "Reading",
  "Romanian",
  "Russian",
  "Sign Language",
  "Spanish",
  "Thai",
  "Turkish",
  "Urdu",
  "Vietnamese",
  "U.S. History",
  "Bible Studies",
  "Classics",
  "Criminal Justice",
  "European History",
  "Geography",
  "Government &amp; Politics",
  "Music History",
  "Philosophy",
  "Political Science",
  "Religion",
  "Social History of Art",
  "World History",
  "Adobe Lightroom",
  "Adobe Photoshop",
  "C",
  "C#",
  "C++",
  "Computer Science",
  "Computer Gaming",
  "Dreamweaver",
  "Fortran",
  "HTML / CSS",
  "Java",
  "Mathematica",
  "MATLAB",
  "Microsoft Access",
  "Microsoft Excel",
  "Microsoft Outlook",
  "Microsoft PowerPoint",
  "Microsoft Project",
  "Microsoft Publisher",
  "Microsoft Word",
  "Networking",
  "Pascal",
  "PHP",
  "Python",
  "QuickBooks",
  "Revit",
  "Ruby",
  "SAS",
  "Sketchup",
  "SPSS",
  "SQL",
  "STATA",
  "UNIX",
  "Video Production",
  "Visual Basic",
  "Graphic Design",
  "Linux",
  "Macintosh",
  "JQuery",
  "Oracle",
  "Perl",
  "R",
  "JavaScript",
  "Angular",
  "Animation",
  "ASP.NET",
  "AutoCAD",
  "ADD/ADHD",
  "Aspergers",
  "Autism",
  "Dyslexia",
  "Etiquette Coach",
  "Hard of Hearing",
  "Homeschool",
  "Life Coach",
  "Social Coach",
  "Special Needs",
  "Architecture",
  "Art History",
  "Art Theory",
  "Ballroom Dancing",
  "Cosmetology",
  "Drawing",
  "Painting",
  "Photography",
  "Salsa Dancing",
  "Theatre",
  "Accounting",
  "Business",
  "Business Coach",
  "Career Development",
  "Finance",
  "Law",
  "Macroeconomics",
  "Marketing",
  "Online Marketing",
  "Microeconomics",
  "Project Management",
  "Tax Preparation",
  "Cello",
  "Clarinet",
  "Music Composition",
  "Drums",
  "Ear Training",
  "Flute",
  "French Horn",
  "General Music",
  "Guitar",
  "Harp",
  "Music Production",
  "Music Theory",
  "Oboe",
  "Piano",
  "Saxophone",
  "Sight Singing",
  "Songwriting",
  "Trombone",
  "Trumpet",
  "Violin",
  "Voice",
  "Ballet",
  "Baseball",
  "Basketball",
  "Bodybuilding",
  "Chess",
  "Cooking",
  "Fitness",
  "Football",
  "Golf",
  "Lacrosse",
  "Martial Arts",
  "Soccer",
  "Softball",
  "Swimming",
  "Tango",
  "Tennis",
  "Track &amp; Field",
  "Volleyball",
  "Water Polo",
  "Yoga",
  "Bass Guitar",
  "Upright Bass",
  "ASVAB",
  "Online",
  "Mandarin",
];

export default subjectsList;
